# Generated by Django 3.1.3 on 2024-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('cargaHs', models.CharField(max_length=2)),
                ('costo', models.CharField(max_length=5)),
            ],
        ),
    ]
