# Generated by Django 3.1.3 on 2024-03-04 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('clientes', '0003_auto_20240219_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='regServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('nomCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.clientes')),
                ('nomServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios')),
            ],
        ),
    ]
