# Generated by Django 3.1.3 on 2024-02-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20240219_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
    ]
